name: progress_state_button
description: A customizable progress button widget for Flutter Android, IOS and Web.
version: 1.0.2
homepage: https://github.com/slm/progress-state-button
issue_tracker: https://github.com/slm/progress-state-button/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
